name: playdate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  audio_video_progress_bar: ^2.0.3
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1
  firebase_database: ^12.1.1
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  just_audio: ^0.10.5
  provider: ^6.1.5+1
  youtube_explode_dart: ^3.0.5
  http: ^1.2.0
  path_provider: ^2.1.5
  youtube_player_flutter: ^9.1.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/loveicon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/loveicon.png"
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: "assets/loveicon.png"
  fullscreen: true

flutter:
  uses-material-design: true
